New-AzPublicIpAddress: Resource 'GatewayIp' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"Prevent assigning public IPs to Virtual machines","id":"/providers/Microsoft.Management/managementGroups/GlobalInnovationLab-Root/providers/Microsoft.Authorization/policyAssignments/e81cc71314484f7583b9b90c"},"policyDefinition":{"name":"Prevent assigning public IPs to Virtual machines","id":"/providers/Microsoft.Management/managementGroups/GlobalInnovationLab-Root/providers/Microsoft.Authorization/policyDefinitions/0ff4af2f-d0a0-4fe2-b5c5-5136d9ce5ca6"}}]'.
StatusCode: 403
ReasonPhrase: Forbidden
ErrorCode: RequestDisallowedByPolicy
Target: GatewayIp
ErrorMessage: Resource 'GatewayIp' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"Prevent assigning public IPs to Virtual machines","id":"/providers/Microsoft.Management/managementGroups/GlobalInnovationLab-Root/providers/Microsoft.Authorization/policyAssignments/e81cc71314484f7583b9b90c"},"policyDefinition":{"name":"Prevent assigning public IPs to Virtual machines","id":"/providers/Microsoft.Management/managementGroups/GlobalInnovationLab-Root/providers/Microsoft.Authorization/policyDefinitions/0ff4af2f-d0a0-4fe2-b5c5-5136d9ce5ca6"}}]'.
OperationID : c57d7404-22c7-43fb-acf8-b1520f4289c9



{
    "status": "Failed",
    "error": {
        "code": "RequestDisallowedByPolicy",
        "message": "Deployments failed due to policy violation: 'Resource 'publicIpgateway-f3a266b5f65c41e59c1497b8569fadfd' was disallowed by policy. Policy identifiers: '[{\"policyAssignment\":{\"name\":\"Prevent assigning public IPs to Virtual machines\",\"id\":\"/providers/Microsoft.Management/managementGroups/GlobalInnovationLab-Root/providers/Microsoft.Authorization/policyAssignments/e81cc71314484f7583b9b90c\"},\"policyDefinition\":{\"name\":\"Prevent assigning public IPs to Virtual machines\",\"id\":\"/providers/Microsoft.Management/managementGroups/GlobalInnovationLab-Root/providers/Microsoft.Authorization/policyDefinitions/0ff4af2f-d0a0-4fe2-b5c5-5136d9ce5ca6\"}}]'.'"
    }
}

{
    "status": "Failed",
    "error": {
        "code": "FailedToConnectWithClusterErrorCode",
        "message": "Unable to connect to cluster management endpoint. Please retry later."
    }
}

{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "BadRequest",
      "message": "The security rules in the Network Security Group '/subscriptions/fa3989a2-0184-4cdc-a1d4-ccb474f86e53/resourceGroups/msresearchcloud/providers/Microsoft.Network/networkSecurityGroups/researchkafka' configured with subnet '/subscriptions/fa3989a2-0184-4cdc-a1d4-ccb474f86e53/resourceGroups/infrastructure/providers/Microsoft.Network/virtualNetworks/default/subnets/default-4' does not allow required inbound and/or outbound connectivity. For more information please visit https://docs.microsoft.com/en-us/azure/hdinsight/hadoop/hdinsight-troubleshoot-invalidnetworksecuritygroupsecurityrules-cluster-creation-fails. or contact support"
    }
  ]
}

I tried creating the kafka cluster again today and I am getting the same error.
{
"code": "DeploymentFailed",
"message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
"details": [
{
"code": "FailedToConnectWithClusterErrorCode",
"message": "Unable to connect to cluster management endpoint. Please retry later."
}
]
}

I have been getting this same error for a while now. Tried to create around 4-5 clusters till now and the result is the same exception.

vnet: default
subnet: default-4
cluster name: kafkaresearch
